# Introduction to Numpy
- Numpy is the core library for scientific computing in Python.
- It provides a high-performance multidimensional array object, and tools for working with these arrays.

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

- The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

- We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a))            # Prints "<type 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                 # Change an element of the array
print (a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])     # Create a rank 2 array
print (b.shape)                     # Prints "(2, 3)"
print (b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[5 2 3]
(2, 3)
(1, 2, 4)


In [3]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


# If you curious about Numpy <a href ="http://cs231n.github.io/python-numpy-tutorial/">click here</a> to go a usefull source